version: "3"

services:
  softether-bridge:
    image: ghcr.io/yude/softether-bridge:main
    build: .
    environment:
      - USERNAME=vpnname
      - PASSWORD=vpnpassword
      - PSK=vpnsecret
      - VPN_SERVER=your.vpn.server:5555
